/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.u1a4_aaronwang;

public class StudentGradesProgram extends javax.swing.JFrame {
    String[][] studentInfo = new String[30][6];
    int curStudent = 0;

    /*
     * Creates new form StudentGradesProgram
     */
    public StudentGradesProgram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        label_title = new javax.swing.JLabel();
        label_name = new javax.swing.JLabel();
        label_grade1 = new javax.swing.JLabel();
        label_grade2 = new javax.swing.JLabel();
        label_grade3 = new javax.swing.JLabel();
        label_grade4 = new javax.swing.JLabel();
        entry_name = new javax.swing.JTextField();
        entry_grade1 = new javax.swing.JTextField();
        entry_grade2 = new javax.swing.JTextField();
        entry_grade3 = new javax.swing.JTextField();
        entry_grade4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputBox = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        notifyBox = new javax.swing.JTextArea();
        listStudentBTN = new javax.swing.JButton();
        addStudentBTN = new javax.swing.JButton();
        studentAvgBTN = new javax.swing.JButton();
        courseAvgBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Grades Calculator");
        setResizable(false);

        background.setBackground(new java.awt.Color(235, 255, 255));

        label_title.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        label_title.setText("Student Grades Calculator");

        label_name.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        label_name.setText("Student Name:");

        label_grade1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        label_grade1.setText("Grade 1:");

        label_grade2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        label_grade2.setText("Grade 2:");

        label_grade3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        label_grade3.setText("Grade 4:");

        label_grade4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        label_grade4.setText("Grade 3:");

        entry_name.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        entry_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entry_nameActionPerformed(evt);
            }
        });

        entry_grade1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        entry_grade2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        entry_grade3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        entry_grade4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        outputBox.setEditable(false);
        outputBox.setBackground(new java.awt.Color(255, 255, 255));
        outputBox.setColumns(20);
        outputBox.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        outputBox.setLineWrap(true);
        outputBox.setRows(5);
        outputBox.setTabSize(1);
        outputBox.setText("Pressing the \"Class List\" button will show your class!");
        outputBox.setWrapStyleWord(true);
        outputBox.setFocusable(false);
        jScrollPane2.setViewportView(outputBox);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        notifyBox.setEditable(false);
        notifyBox.setBackground(new java.awt.Color(255, 255, 255));
        notifyBox.setColumns(20);
        notifyBox.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        notifyBox.setForeground(new java.awt.Color(255, 0, 62));
        notifyBox.setLineWrap(true);
        notifyBox.setRows(1);
        notifyBox.setWrapStyleWord(true);
        notifyBox.setFocusable(false);
        jScrollPane1.setViewportView(notifyBox);

        listStudentBTN.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        listStudentBTN.setText("Class List");
        listStudentBTN.setFocusable(false);
        listStudentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listStudentBTNActionPerformed(evt);
            }
        });

        addStudentBTN.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        addStudentBTN.setText("Add Info");
        addStudentBTN.setFocusable(false);
        addStudentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentBTNActionPerformed(evt);
            }
        });

        studentAvgBTN.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        studentAvgBTN.setText("Student Avg.");
        studentAvgBTN.setFocusable(false);
        studentAvgBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentAvgBTNActionPerformed(evt);
            }
        });

        courseAvgBTN.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        courseAvgBTN.setText("Course Avg.");
        courseAvgBTN.setFocusable(false);
        courseAvgBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseAvgBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(addStudentBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listStudentBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(label_name)
                                .addGap(18, 18, 18)
                                .addComponent(entry_name, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_grade1)
                                    .addComponent(label_grade2)
                                    .addComponent(label_grade4)
                                    .addComponent(label_grade3))
                                .addGap(59, 59, 59)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(entry_grade2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(entry_grade1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(entry_grade3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(entry_grade4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(studentAvgBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(courseAvgBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(label_title, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(label_title, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_name)
                            .addComponent(entry_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_grade1)
                            .addComponent(entry_grade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_grade2)
                            .addComponent(entry_grade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_grade4)
                            .addComponent(entry_grade3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_grade3)
                            .addComponent(entry_grade4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStudentBTN)
                    .addComponent(listStudentBTN)
                    .addComponent(studentAvgBTN)
                    .addComponent(courseAvgBTN))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void entry_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entry_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entry_nameActionPerformed
    private String capitalize(String s) {
        return s.substring(0, 1).toUpperCase() + s.substring(1).toLowerCase();
    }
    private void clearInput() {
        entry_name.setText("");
        entry_grade1.setText("");
        entry_grade2.setText("");
        entry_grade3.setText("");
        entry_grade4.setText("");    
    }
    private String[] grabName (javax.swing.JTextField textbox) {
        return textbox.getText().trim().split("\\s+");
    }
    private void addStudentBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentBTNActionPerformed
        notifyBox.setText("");
        
        // Declarations
        String[] potentialName = grabName(entry_name);
        double grade1, grade2, grade3, grade4;
        
        // If all boxes are unfilled, return.
        if(entry_name.getText().trim().equals("") && entry_grade1.getText().trim().equals("") && entry_grade2.getText().trim().equals("") && entry_grade3.getText().trim().equals("") && entry_grade4.getText().trim().equals("")) {
            notifyBox.setText("Please fill out the fields!");
            return;
        }
        // If classlist is 30 (full), return out.
        if(curStudent == 30) {
            notifyBox.setText("Your classlist is full!");
            return;
        }
        
        // If there is no first and last name, return out.
        if(potentialName.length < 2) {
            notifyBox.setText("Please enter a first and last name separated by spaces!");
            return;
        }
        
        // Iterate through studentInfo and check the first and second element against their respective elements in potentialName
        // If both match, there is a duplicate student; return out.
        for(String[] array : studentInfo) {
            if(potentialName[0].equalsIgnoreCase(array[0]) && potentialName[1].equalsIgnoreCase(array[1])) {
                notifyBox.setText("That student already exists!");
                return;
            }
        }
        
        // Check if entered grades are valid. If caught, return out.
        try{
            grade1 = Double.parseDouble(entry_grade1.getText());
            grade2 = Double.parseDouble(entry_grade2.getText());
            grade3 = Double.parseDouble(entry_grade3.getText());
            grade4 = Double.parseDouble(entry_grade4.getText());
            
            if(grade1 < 0 || grade1 > 100 || grade2 < 0 || grade2 > 100 || grade3 < 0 || grade3 > 100 || grade4 < 0 || grade4 > 100) {
                notifyBox.setText("Grades can only be in between 0 and 100%!");
                return;
            }
        } catch (NumberFormatException nfe) {
            notifyBox.setText("Please enter valid grade input!");
            return;
        }
        
        // Sets studentInfo; at this point in the code, all entries are valid entries.
        studentInfo[curStudent][0] = capitalize(potentialName[0]);
        studentInfo[curStudent][1] = capitalize(potentialName[1]);
        studentInfo[curStudent][2] = grade1 + "";
        studentInfo[curStudent][3] = grade2 + "";
        studentInfo[curStudent][4] = grade3 + "";
        studentInfo[curStudent][5] = grade4 + "";
        
        // Clears all entry boxes.
        clearInput();
        notifyBox.setText("Student " + studentInfo[curStudent][0] + " " + studentInfo[curStudent][1] + " has been entered.");
        curStudent++;
    }//GEN-LAST:event_addStudentBTNActionPerformed

    private void listStudentBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listStudentBTNActionPerformed
        notifyBox.setText("");
        String output = "", fixPlural = "s";
 
        // If classlist empty, return.
        if(curStudent == 0) {
            notifyBox.setText("You have no registered students!");
            return;
        } else if(curStudent == 1) {
            fixPlural = "";
        }
        
        // Iterate through and add student info to output.
        for(int i = 0; i < curStudent; i++) {
            output += studentInfo[i][0] + " " + studentInfo[i][1] + "\n\t1: " + studentInfo[i][2]+ "%\n\t2: " + studentInfo[i][3]+ "%\n\t3: " + studentInfo[i][4]+ "%\n\t4: " + studentInfo[i][5] + "%\n";
        }
        outputBox.setText(output);
        notifyBox.setText("You have " + curStudent + " student" + fixPlural + " in your class.");
    }//GEN-LAST:event_listStudentBTNActionPerformed

    private void studentAvgBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentAvgBTNActionPerformed
        notifyBox.setText("");

        // Initialization.
        boolean isInArray = false;
        double average = 0;
        String firstName = "", lastName = "";
        // Grabs user entry and splits it into a potential name of a student
        String[] potentialName = grabName(entry_name);
        
        // Check if a valid name has been entered.
        if(potentialName.length < 2) {
            notifyBox.setText("Please enter a first and last name separated by spaces!");
            return;
        }
        
        // Determine if entered student is in the 2D array.
        for(String[] array : studentInfo) {
            if(array[0].equalsIgnoreCase(potentialName[0]) && array[1].equalsIgnoreCase(potentialName[1])) {
                isInArray = true;
                firstName = potentialName[0]; 
                lastName = potentialName[1];
                average = Math.round((
                        Double.parseDouble(array[2]) + 
                        Double.parseDouble(array[3]) +
                        Double.parseDouble(array[4]) + 
                        Double.parseDouble(array[5]) )
                        / 4.0
                        * 100 ) 
                        / 100.0;
                
                break;
            }
        }
        
        // If the student is not in array, return.
        if(!isInArray) {
            notifyBox.setText("The student " + capitalize(potentialName[0]) + "  " + capitalize(potentialName[1]) + " was not found!");
            return;
        }
        
        outputBox.setText("The average grade of " + firstName + " " + lastName + " is " + average + "%.");
        clearInput();
        
    }//GEN-LAST:event_studentAvgBTNActionPerformed

    private void courseAvgBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseAvgBTNActionPerformed
        double courseAvg = 0;
        notifyBox.setText("");
        
        // Check if array is empty.
        if(curStudent == 0) {
            notifyBox.setText("You have no registered students!");
            return;
        }
        
        for(int i = 0; i < curStudent; i++) {
            courseAvg += Double.parseDouble(studentInfo[i][2]) + 
                         Double.parseDouble(studentInfo[i][3]) + 
                         Double.parseDouble(studentInfo[i][4]) + 
                         Double.parseDouble(studentInfo[i][5]);
        }
        
        courseAvg = Math.round((courseAvg / (curStudent * 4)) * 100) / 100.0;
        
        outputBox.setText("The course average for this class is " + courseAvg + "%.");
    }//GEN-LAST:event_courseAvgBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentGradesProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentGradesProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentGradesProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentGradesProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentGradesProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudentBTN;
    private javax.swing.JPanel background;
    private javax.swing.JButton courseAvgBTN;
    private javax.swing.JTextField entry_grade1;
    private javax.swing.JTextField entry_grade2;
    private javax.swing.JTextField entry_grade3;
    private javax.swing.JTextField entry_grade4;
    private javax.swing.JTextField entry_name;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_grade1;
    private javax.swing.JLabel label_grade2;
    private javax.swing.JLabel label_grade3;
    private javax.swing.JLabel label_grade4;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_title;
    private javax.swing.JButton listStudentBTN;
    private javax.swing.JTextArea notifyBox;
    private javax.swing.JTextArea outputBox;
    private javax.swing.JButton studentAvgBTN;
    // End of variables declaration//GEN-END:variables
}
